# Generated by Django 4.0.6 on 2022-07-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_allbooks_alter_loans_book_delete_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loans',
            name='loan_date',
        ),
        migrations.AddField(
            model_name='allbooks',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='allbooks',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
